// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxInput represents a transaction input
type TxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`                   // The ID of the transaction containing the output to spend
	Vout          int32                  `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`                  // The index of the output in the transaction
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`         // The digital signature that proves ownership
	PubKey        []byte                 `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"` // The public key of the sender
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TxInput) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *TxInput) GetVout() int32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *TxInput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TxInput) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

// TxOutput represents a transaction output
type TxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`                              // The amount of coins
	PubKeyHash    []byte                 `protobuf:"bytes,2,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"` // The hash of the public key (address) of the recipient
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TxOutput) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

// Transaction represents a blockchain transaction
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Transaction ID
	Vin           []*TxInput             `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`   // Transaction inputs
	Vout          []*TxOutput            `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"` // Transaction outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetVin() []*TxInput {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Transaction) GetVout() []*TxOutput {
	if x != nil {
		return x.Vout
	}
	return nil
}

// TxOutputList is a wrapper for serializing arrays of TxOutput
type TxOutputList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*TxOutput            `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutputList) Reset() {
	*x = TxOutputList{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutputList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutputList) ProtoMessage() {}

func (x *TxOutputList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutputList.ProtoReflect.Descriptor instead.
func (*TxOutputList) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TxOutputList) GetOutputs() []*TxOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_proto_transaction_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"#proto/transaction/transaction.proto\x12\vtransaction\"h\n" +
	"\aTxInput\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\x05R\x04vout\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x17\n" +
	"\apub_key\x18\x04 \x01(\fR\x06pubKey\"B\n" +
	"\bTxOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12 \n" +
	"\fpub_key_hash\x18\x02 \x01(\fR\n" +
	"pubKeyHash\"p\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x03vin\x18\x02 \x03(\v2\x14.transaction.TxInputR\x03vin\x12)\n" +
	"\x04vout\x18\x03 \x03(\v2\x15.transaction.TxOutputR\x04vout\"?\n" +
	"\fTxOutputList\x12/\n" +
	"\aoutputs\x18\x01 \x03(\v2\x15.transaction.TxOutputR\aoutputsB?Z=github.com/OmSingh2003/decentralized-ledger/proto/transactionb\x06proto3"

var (
	file_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_proto_rawDescData []byte
)

func file_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_transaction_proto_rawDescData
}

var file_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_transaction_transaction_proto_goTypes = []any{
	(*TxInput)(nil),      // 0: transaction.TxInput
	(*TxOutput)(nil),     // 1: transaction.TxOutput
	(*Transaction)(nil),  // 2: transaction.Transaction
	(*TxOutputList)(nil), // 3: transaction.TxOutputList
}
var file_proto_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.Transaction.vin:type_name -> transaction.TxInput
	1, // 1: transaction.Transaction.vout:type_name -> transaction.TxOutput
	1, // 2: transaction.TxOutputList.outputs:type_name -> transaction.TxOutput
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_proto_init() }
func file_proto_transaction_transaction_proto_init() {
	if File_proto_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_proto = out.File
	file_proto_transaction_transaction_proto_goTypes = nil
	file_proto_transaction_transaction_proto_depIdxs = nil
}
