// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/block/block.proto

package block

import (
	transaction "github.com/OmSingh2003/decentralized-ledger/proto/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block represents a block in the blockchain
type Block struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Timestamp       int64                      `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // Records when block was created/mined
	Transactions    []*transaction.Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`                                // stores Transactions
	PrevBlockHash   []byte                     `protobuf:"bytes,3,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`       // Stores the Hash of previous Block in the chain
	Hash            []byte                     `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`                                                // Stores the Hash of current block in the chain
	Nonce           int32                      `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                                             // Number used in proof of work
	Bits            int64                      `protobuf:"varint,6,opt,name=bits,proto3" json:"bits,omitempty"`                                               // Stores the difficulty target bits for this block
	ValidatorPubKey []byte                     `protobuf:"bytes,7,opt,name=validator_pub_key,json=validatorPubKey,proto3" json:"validator_pub_key,omitempty"` // Public key of the validator who signed this block
	Signature       []byte                     `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                      // Signature of the block by the validator
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_block_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_block_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_block_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetTransactions() []*transaction.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Block) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *Block) GetValidatorPubKey() []byte {
	if x != nil {
		return x.ValidatorPubKey
	}
	return nil
}

func (x *Block) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_block_block_proto protoreflect.FileDescriptor

const file_proto_block_block_proto_rawDesc = "" +
	"\n" +
	"\x17proto/block/block.proto\x12\x05block\x1a#proto/transaction/transaction.proto\"\x93\x02\n" +
	"\x05Block\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12<\n" +
	"\ftransactions\x18\x02 \x03(\v2\x18.transaction.TransactionR\ftransactions\x12&\n" +
	"\x0fprev_block_hash\x18\x03 \x01(\fR\rprevBlockHash\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x05R\x05nonce\x12\x12\n" +
	"\x04bits\x18\x06 \x01(\x03R\x04bits\x12*\n" +
	"\x11validator_pub_key\x18\a \x01(\fR\x0fvalidatorPubKey\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignatureB9Z7github.com/OmSingh2003/decentralized-ledger/proto/blockb\x06proto3"

var (
	file_proto_block_block_proto_rawDescOnce sync.Once
	file_proto_block_block_proto_rawDescData []byte
)

func file_proto_block_block_proto_rawDescGZIP() []byte {
	file_proto_block_block_proto_rawDescOnce.Do(func() {
		file_proto_block_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_block_block_proto_rawDesc), len(file_proto_block_block_proto_rawDesc)))
	})
	return file_proto_block_block_proto_rawDescData
}

var file_proto_block_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_block_block_proto_goTypes = []any{
	(*Block)(nil),                   // 0: block.Block
	(*transaction.Transaction)(nil), // 1: transaction.Transaction
}
var file_proto_block_block_proto_depIdxs = []int32{
	1, // 0: block.Block.transactions:type_name -> transaction.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_block_block_proto_init() }
func file_proto_block_block_proto_init() {
	if File_proto_block_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_block_block_proto_rawDesc), len(file_proto_block_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_block_block_proto_goTypes,
		DependencyIndexes: file_proto_block_block_proto_depIdxs,
		MessageInfos:      file_proto_block_block_proto_msgTypes,
	}.Build()
	File_proto_block_block_proto = out.File
	file_proto_block_block_proto_goTypes = nil
	file_proto_block_block_proto_depIdxs = nil
}
